name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 10.x
    - run: cd ./functions
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@1.1.0
      with:
        args: |
          install
          global add tslint
    - run: cd ../
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.1.0
      with:
        args: deploy --only functions
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
